### ISSUE TITLE
German Umlaute are being treated as their latin counterparts

### ISSUE THREAD

**Issue by kraibse** [mProjectsCode/obsidian-lemons-search-plugin#5]
Hello there,

The plugin works great and mostly as I expected it to work. The one exception so far is that the plugin treats Umlaute like:

- ä
- ö
- ü

As their non-Umlaut counterpart a, o, u and respective. This means that I find more results than are actually relevant to me.

**Comment by mProjectsCode** [comment]
Unicode characters are handled by the rust library that I use. That library decided to use the first code point of a grapheme for matching, meaning that any special unicode decorations like the german double dots or french accents are ignored.
Since this is done by the library and not my code, this will not be changed.
